"""add credentials to app_settings

Revision ID: 0c27aee33215
Revises: 0005
Create Date: 2026-06-07 09:32:37.944468+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c27aee33215'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('last_successful_upload_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('app_settings', sa.Column('gcp_service_account_json', sa.JSON(), nullable=True))
    op.add_column('app_settings', sa.Column('service_account_email', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_student_results_enrollment'), table_name='student_results')
    op.create_index(op.f('ix_student_results_student_enrollment_id'), 'student_results', ['student_enrollment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_results_student_enrollment_id'), table_name='student_results')
    op.create_index(op.f('ix_student_results_enrollment'), 'student_results', ['student_enrollment_id'], unique=False)
    op.drop_column('app_settings', 'service_account_email')
    op.drop_column('app_settings', 'gcp_service_account_json')
    op.drop_column('app_settings', 'last_successful_upload_at')
    # ### end Alembic commands ###
