"""add_student_creation_counters_to_import_batch

Revision ID: 2d944c71a398
Revises: 5b3288a52ff4
Create Date: 2026-06-07 14:43:58.448668+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d944c71a398'
down_revision: Union[str, None] = '5b3288a52ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_batches', sa.Column('students_created', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('import_batches', sa.Column('existing_students_matched', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('import_batches', sa.Column('enrollments_created', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_batches', 'enrollments_created')
    op.drop_column('import_batches', 'existing_students_matched')
    op.drop_column('import_batches', 'students_created')
    # ### end Alembic commands ###
