"""add encrypted gcp credentials

Revision ID: 5b3288a52ff4
Revises: 0c27aee33215
Create Date: 2026-06-07 11:07:20.622038+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b3288a52ff4'
down_revision: Union[str, None] = '0c27aee33215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('gcp_credentials_encrypted', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'gcp_credentials_encrypted')
    # ### end Alembic commands ###
